Subscriber/subscribtion implementation
Ingloryon/SDP_PolyChef pull request #152
Opened 2020-04-28 14:54 UTC by simhayoz

2020-04-28 15:02 UTC, simhayoz commented
TODO:

- Fix bug: can click on own profile while visiting another profile
- Add and remove current user to the other user subscribers on click to the subscribe button (see _UserProfileFragment_ line 101 and 104, I ask @yanickpauloamaro on how we can update another user from the current user)
- Add author to the recipe and add onclick to profile fragment (similar to _UserMiniatureAdapter_ line 89-100)
- Tests

2020-04-30 15:11 UTC, yanickpauloamaro requested changes
Except the navigation issues, it seems good to me.
The UserListFragment super class makes it much cleaner than with the recipeMiniatures, good job!

2020-04-30 15:11 UTC, yanickpauloamaro commented on app/src/main/java/ch/epfl/polychef/fragments/FullRecipeFragment.java
> +                    fragMana.beginTransaction().replace(containerId, userProfileFragment).addToBackStack(null).commit();
Should use a navigation controller to navigate between fragments. Otherwise there will be navigation problems like we had before.

2020-04-30 15:11 UTC, yanickpauloamaro commented on app/src/main/java/ch/epfl/polychef/users/UserStorage.java
> +
I would have removed the other version, or at least make it call this one, like:
`public void updateUser() {
updateUser(connectedUser);
}`

2020-04-30 15:11 UTC, yanickpauloamaro commented on app/src/main/java/ch/epfl/polychef/users/UserStorage.java
> +    }
Very similar to what is done in initializeUserFromAuthenticatedUser. Could refactor later to reduce duplication of code (if we have time).

2020-04-30 15:11 UTC, yanickpauloamaro commented on app/src/main/java/ch/epfl/polychef/utils/UserMiniatureAdapter.java
> +            fragMana.beginTransaction().replace(fragmentContainerID, userProfileFragment).addToBackStack(null).commit();
We know the context is the homepage, we should use the navController to avoid problems.
I will open a new branch to fix all the navigation problems after this is merged.

2020-04-30 17:02 UTC, simhayoz commented on app/src/main/java/ch/epfl/polychef/fragments/FullRecipeFragment.java
> +                    fragMana.beginTransaction().replace(containerId, userProfileFragment).addToBackStack(null).commit();
I added a task to fix these different bugs (see #156 )

2020-04-30 17:03 UTC, simhayoz commented on app/src/main/java/ch/epfl/polychef/utils/UserMiniatureAdapter.java
> +            fragMana.beginTransaction().replace(fragmentContainerID, userProfileFragment).addToBackStack(null).commit();
I added a task to fix these different bugs (see #156 )

2020-04-30 17:04 UTC, simhayoz commented on app/src/main/java/ch/epfl/polychef/users/UserStorage.java
> +    }
Good point for a later refactor

2020-04-30 17:14 UTC, simhayoz commented on app/src/main/java/ch/epfl/polychef/users/UserStorage.java
> +
You are right, it is now fixed

2020-04-30 17:20 UTC, yanickpauloamaro commented on app/src/main/java/ch/epfl/polychef/fragments/FullRecipeFragment.java
> +                    fragMana.beginTransaction().replace(containerId, userProfileFragment).addToBackStack(null).commit();
Thanks

2020-04-30 17:20 UTC, yanickpauloamaro commented on app/src/main/java/ch/epfl/polychef/users/UserStorage.java
> +
Nice, thanks!

2020-04-30 17:20 UTC, yanickpauloamaro approved these changes

2020-04-30 18:08 UTC, Ingloryon approved these changes

2020-04-30 20:01 UTC, merged