make the app work when not connected to internet
Ingloryon/SDP_PolyChef pull request #232
Opened 2020-05-22 10:28 UTC by wilderino

2020-05-22 14:55 UTC, ChapatteMateo approved these changes

2020-05-23 08:34 UTC, yanickpauloamaro requested changes
~~There are a few places where I don't understand how you prevent the queries from being sent, since you only send a toast. (in UserProfileFragment, OnlineMiniaturesFragment)~~

2020-05-23 08:34 UTC, yanickpauloamaro commented on app/src/main/java/ch/epfl/polychef/fragments/UserProfileFragment.java
> +
What about
```
if(dynamicRecipeList.isEmpty()){
            getNextRecipes();
}
```
at the bottom of this method? Shouldn't you prevent `getNRecipes` from being called?

2020-05-23 09:05 UTC, yanickpauloamaro commented on app/src/main/java/ch/epfl/polychef/fragments/UserProfileFragment.java
> +
Okay, I thought the queries were the reason the app crashed, if that's not the case then it's fine to let the queries through

2020-05-23 09:06 UTC, yanickpauloamaro approved these changes

2020-05-23 09:06 UTC, merged