Basic recipe
Ingloryon/SDP_PolyChef pull request #44
Opened 2020-03-04 19:11 UTC by Ingloryon

First pull request to check what Code Climate has to say.

2020-03-08 13:46 UTC, Ingloryon commented
Si j'avais j'avais approuvé les smells CodeClimate quand je les avais corrigées la semaine derniere quand on hesitait à merge et du coup il marque toujours validé alors qu'on en a pleins de nouvelles crées cette semaine.

2020-03-12 15:11 UTC, simhayoz requested changes

2020-03-12 15:11 UTC, simhayoz commented on app/src/androidTest/java/ch/epfl/polychef/EntryPageTest.java
> +
Too much space between import and class definition

2020-03-12 15:11 UTC, simhayoz commented on app/src/androidTest/java/ch/epfl/polychef/FullRecipeFragmentTest.java
> +import org.junit.Rule;
Import order

2020-03-12 15:11 UTC, simhayoz commented on app/src/androidTest/java/ch/epfl/polychef/RecipeActTest.java
> +public class RecipeActTest {
This file does not test anything, is it really useful?

2020-03-12 15:11 UTC, simhayoz commented on app/src/androidTest/java/ch/epfl/polychef/RecipeTest.java
> +                assertTrue(ingredient.getQuantity() == 150d);
We should use assertThat or assertEquals for better error message instead of assertTrue (same multiple time in this file)

2020-03-12 15:11 UTC, simhayoz commented on app/src/androidTest/java/ch/epfl/polychef/IngredientTests.java
> +        assertTrue(ingredient.getQuantity() == 300d);
We should use assertThat or assertEquals for better error message instead of assertTrue (same multiple time in this file)

2020-03-12 15:11 UTC, simhayoz commented on app/src/androidTest/java/ch/epfl/polychef/RatingTest.java
> +        assertTrue(rating.ratingAverage() == 2.25);
We should use assertThat or assertEquals for better error message instead of assertTrue (same multiple time in this file)

2020-03-12 15:11 UTC, simhayoz commented on app/src/main/java/ch/epfl/polychef/recipe/Ingredient.java
> +        //TODO should check quantity depending on unit (0 is only ok for NONE and NO_UNIT)
We can replace the TODO by the implementation here

2020-03-12 15:11 UTC, simhayoz commented on app/src/main/java/ch/epfl/polychef/recipe/OfflineRecipes.java
> +    public List<Recipe> getCopy() {
The name should reflect what it does, for example: `getOfflineRecipes()`

2020-03-12 15:11 UTC, simhayoz commented on app/src/test/java/ch/epfl/polychef/TestingUnitTest.java
> +public class TestingUnitTest {
We could delete this file

2020-03-12 15:23 UTC, ChapatteMateo approved these changes

2020-03-12 15:23 UTC, ChapatteMateo commented on app/src/androidTest/java/ch/epfl/polychef/RecipeActTest.java
> +    }
C'est pas sencé être comme ça dans la version finale, si ?

2020-03-12 15:33 UTC, ChapatteMateo approved these changes

2020-03-12 15:36 UTC, simhayoz approved these changes

2020-03-12 15:37 UTC, ChapatteMateo approved these changes

2020-03-12 15:48 UTC, Ingloryon commented on app/src/androidTest/java/ch/epfl/polychef/RecipeActTest.java
> +    }
Heu oui non c'etait la classe ou je comptais test un classe de Lucas mais au final elle existe plus ^^

2020-03-12 16:05 UTC, merged